### ISSUE TITLE
I can't implement the repo in my project

### ISSUE THREAD

**Issue by milliongashawbeza** [AsynctaskCoffee/AndroidOfflineMapLibrary#2]
I don't use NDK in my project but it gives me a sync 
failed with a log "UNKNOWN NDK version " .

**Comment by AsynctaskCoffee** [comment]
Hello sorry for late reply. Library uses NDK based code. So you have to update and impletemet NDK. Did you try after updating your NDK ? If problem still exists please mail me at contact@egemenozogul.com . Thank you!
