### ISSUE TITLE
how to add location searches with offline maps?

### ISSUE THREAD

**Issue by AchmadFadillah** [AsynctaskCoffee/AndroidOfflineMapLibrary#3]
I want to make an offline map that can search for locations offline whether it can? and how solution.
Thank you..

**Comment by AsynctaskCoffee** [comment]
Hello,

You should have local JSON files which contains name tag and locations. You may use Kaggle or Google Places Api for JSON datasets. Asuuming that you want to use offline map so your locations JSON wont be large.

Good luck :)
