### ISSUE TITLE
Assets cannot be copied

### ISSUE THREAD

**Issue by asafeca** [AsynctaskCoffee/AndroidOfflineMapLibrary#4]
Hi?
Thanks for your solution and I am testing it.
Everything looks fine but the Map does not load and the message : "Assets cannot be copied!" is thrown.
Any idea how to solve it?

**Comment by AsynctaskCoffee** [comment]
```
private static String[] PERMISSIONS = {
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.ACCESS_FINE_LOCATION,
};
```

Hi! I also seen ur message in dev.to 👍 , please try to have this permissions before your map initialize code. If this does not work for you, you should edit fileutils class. (Simply: Write code to "move asset files to sd card" with non-deprecated way)

Some parts of this library must be updated. I will rewrite entire library in Kotlin soon. Thank you for your feedback !

**Comment by asafeca** [comment]
Thanks @AsynctaskCoffee, I have it working now. But it only works on real device not on an Emulator, at least for me. Thanks
