### ISSUE TITLE
AndroidOfflineMapLibrary for Kotlin

### ISSUE THREAD

**Issue by asafeca** [AsynctaskCoffee/AndroidOfflineMapLibrary#5]
Hi, I tested the java code and it's working. But when using Kotlin it does not work. I keep receiving log messages saying cannot find cache.db. Any idea?, please...

**Comment by AsynctaskCoffee** [comment]
I will rewrite this lib on kotlin soon.

**Comment by asafeca** [comment]
Okay. But now I can see the map and the markers, just the polylines are missing.
