### ISSUE TITLE
get Altitude

### ISSUE THREAD

**Issue by git1991** [AsynctaskCoffee/AndroidOfflineMapLibrary#6]
Hello
How can I find the height of any coordinate?
Thanks

**Comment by AsynctaskCoffee** [comment]
Hi, offline db does not hold altitudes. Sorry. You have to crawl and save the altitude datas from several apis with your own algorithm.

**Comment by git1991** [comment]
Can you help me how can I find the height of a coordinate?
thanks
فاtt
فد

**Comment by AsynctaskCoffee** [comment]
Check https://github.com/Jorl17/open-elevation/blob/master/docs/api.md this repo. It will help you.
